version: "3.9"
services:
 postgres:
   image: postgres:latest
   environment:
     POSTGRES_DB: "messaging-service"
     POSTGRES_USER: "messaging-service"
     POSTGRES_PASSWORD: "postgres"
   ports:
     - "1234:5432"
  